name: Send Telegram CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.ANDROID_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            /build daysmatter-android
